{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 6}, "tests": {"0": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_navigate_to_bus", "rerun": "0"}, "1": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_select_src_city", "rerun": "0"}, "2": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_select_dest_city", "rerun": "0"}, "3": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_select_depart_date", "rerun": "0"}, "4": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_click_to_search_button", "rerun": "0"}, "5": {"status": "ERROR", "message": "request = <SubRequest 'get_driver' for <Function test_navigate_to_bus>>, pytestconfig = <_pytest.config.Config object at 0x000001C20BA1DF40>\n\n    @pytest.fixture(scope=\"class\")\n    def get_driver(request, pytestconfig):\n        browser = pytestconfig.getoption(\"browser\")\n        headless = pytestconfig.getoption(\"headless\")\n        if browser and headless:\n            wf = WebdriverFactory(browser, headless)\n        elif browser:\n            wf = WebdriverFactory(browser, headless=False)\n        else:\n            wf = WebdriverFactory('chrome', headless=False)\n>       driver = wf.get_driver_instance()\n\ntests\\conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbase\\webdriver_factory.py:30: in get_driver_instance\n    self.driver = webdriver.Firefox(options=edge_opt)\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:63: in __init__\n    self.service.start()\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:106: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.firefox.service.Service object at 0x000001C20EAFAA20>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\Deepesh Yadav\\.cache\\selenium\\msedgedriver\\win64\\137.0.3296.93\\msedgedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:119: WebDriverException\n", "test_name": "test_select_bus_to_travel", "rerun": "0"}}, "suite_name": "tests/bus_booking/test_bus_booking.py"}}}, "date": "June 24, 2025", "start_time": 1750778879.746845, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "6", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}